### ISSUE TITLE
Launcher not launching

### ISSUE THREAD

**Issue by DaTravBoo** [nothanley/AEW-FF-Mod-Bypass#1]
Every time I try to launch the game using this launcher, it acts like it's going to open and then just closes.  any suggestions?

**Comment by nothanley** [comment]
Where are you placing your file? What game version are you on?

**Comment by DaTravBoo** [comment]
In the win64 folder. 1.02 I believe

**Comment by jumcum777** [comment]
sorry to necro post, but has this been resolved in any way? am also having the same issue on game version 1.02

**Comment by nothanley** [comment]
If you're having issues with the launcher try the exe patcher in the following link. It patches the file directly so don't launch through the mod launcher if you use this. ( https://github.com/nothanley/AEW-FF-Mod-Bypass/releases/tag/v1.0 )

**Comment by jumcum777** [comment]
thank u so much but i already figured out i had to run it in admin mode, my
comp is weird and i need to do the same with doom eternal as well, its inly
certain games or exes lol. thank u so much though and also thank u for the
work on the patched exe
